# Site settings
title: NYPD Search Question Frisk
tag_text: nypd-sqf
description: Data Visualization of NYPD Search, Question, Frisk data

# Build settings
markdown: kramdown
highlighter: pygments

exclude: ["README.md"]
